In [ ]:
!pip install sidetable
import pandas as pd
import numpy as np
import sidetable as stb

pd.options.display.max_columns = None

Collecting sidetable
  Downloading sidetable-0.9.1-py3-none-any.whl.metadata (45 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.4/45.4 kB 1.9 MB/s eta 0:00:00
Requirement already satisfied: pandas>=1.0 in /usr/local/lib/python3.11/dist-packages (from sidetable) (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0->sidetable) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0->sidetable) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0->sidetable) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0->sidetable) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0->sidetable) (1.17.0)
Downloading sidetable-0.9.1-py3-none-any.whl (19 kB)
Installing collected packages: sidetable
Successfully installed sidetable-0.9.1

In [ ]:
df = pd.read_csv("/content/COPIA- atenciones_oficina_publica_de_empleo_ope.csv")
df.head(100)

,edad,sexo,etnia,discapacidad,victima,población_campesina,estado_civil,nivel_escolaridad,cabeza_de_hogar,orientación_sexual,caracterizacion_ciudadano,empleado,estrato,barrio_vereda_ciudadano,comuna_ciudadano,zona_ciudadano,nombre_del_beneficio_otorgado,fecha_de_beneficio_dia,fecha_de_beneficio_mes,fecha_de_beneficio_año,sede_que_otorga_el_beneficio,fase_del_proceso,fase_del_emprendimiento,como_se_enteró_del_servicio,subsecretaría_dirección,nombre_de_la_unidad_o_programa,nombre_del_proyecto
0,45.0,femenino,otros,no,no,no,soltero,tecnico,si,heterosexual,otro,no,3,bello,a1-bello / fuera de medellín,NaN,9. intermediacion laboral (registro hoja de v...,16,8,2017,cam - alcaldia de medellin,1. inscripción,no aplica,evento,subsecretaría de creación y fortalecimiento em...,ope,oficina pública de empleo
1,45.0,femenino,otros,no,no,no,soltero,tecnico,si,heterosexual,otro,no,3,bello,a1-bello / fuera de medellín,NaN,9. intermediacion laboral (registro hoja de v...,16,8,2017,cam - alcaldia de medellin,1. inscripción,no aplica,evento,subsecretaría de creación y fortalecimiento em...,ope,oficina pública de empleo
2,45.0,femenino,otros,no,no,no,soltero,tecnico,si,heterosexual,otro,no,3,bello,a1-bello / fuera de medellín,NaN,9. intermediacion laboral (registro hoja de v...,16,8,2017,cam - alcaldia de medellin,1. inscripción,no aplica,evento,subsecretaría de creación y fortalecimiento em...,ope,oficina pública de empleo
3,25.0,femenino,otros,no,no,no,casado,tecnologo,no,heterosexual,otro,no,2,villa hermosa,08-villa hermosa,centro-oriental,9. intermediacion laboral (registro hoja de v...,17,9,2017,ope villa hermosa,1. inscripción,no aplica,voz a voz,subsecretaría de creación y fortalecimiento em...,ope,oficina pública de empleo
4,30.0,femenino,otros,no,no,no,soltero,bachiller,si,heterosexual,otro,no,2,villa hermosa,08-villa hermosa,centro-oriental,9. intermediacion laboral (registro hoja de v...,15,9,2017,ope villa hermosa,1. inscripción,no aplica,evento,subsecretaría de creación y fortalecimiento em...,ope,oficina pública de empleo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,55.0,masculino,otros,no,no,no,casado,primaria,si,heterosexual,otro,no,2,robledo,07-robledo,nor-occidental,9. intermediacion laboral (actualización hoja...,17,8,2017,cam - alcaldia de medellin,5. prestación del servicio,no aplica,evento,subsecretaría de creación y fortalecimiento em...,ope,oficina pública de empleo
96,55.0,masculino,otros,no,no,no,casado,primaria,si,heterosexual,otro,no,2,robledo,07-robledo,nor-occidental,9. intermediacion laboral (actualización hoja...,17,8,2017,cam - alcaldia de medellin,5. prestación del servicio,no aplica,evento,subsecretaría de creación y fortalecimiento em...,ope,oficina pública de empleo
97,55.0,masculino,otros,no,no,no,casado,primaria,si,heterosexual,otro,no,2,robledo,07-robledo,nor-occidental,9. intermediacion laboral (actualización hoja...,17,8,2017,cam - alcaldia de medellin,5. prestación del servicio,no aplica,evento,subsecretaría de creación y fortalecimiento em...,ope,oficina pública de empleo
98,55.0,masculino,otros,no,no,no,casado,primaria,si,heterosexual,otro,no,3,robledo,07-robledo,nor-occidental,2. orientacion (ope),26,8,2017,ope robledo,2.orientación,no aplica,feria,subsecretaría de creación y fortalecimiento em...,ope,oficina pública de empleo
99,55.0,masculino,otros,no,no,no,casado,primaria,si,heterosexual,otro,no,3,robledo,07-robledo,nor-occidental,9. intermediacion laboral (actualización hoja...,26,8,2017,ope robledo,1. inscripción,no aplica,feria,subsecretaría de creación y fortalecimiento em...,ope,oficina pública de empleo

In [ ]:
# Comprobamos los nulos
df.stb.missing()

                                missing  total    percent
zona_ciudadano                    56352  61620  91.450828
edad                               5705  61620   9.258358
sexo                                  0  61620   0.000000
discapacidad                          0  61620   0.000000
victima                               0  61620   0.000000
población_campesina                   0  61620   0.000000
estado_civil                          0  61620   0.000000
nivel_escolaridad                     0  61620   0.000000
cabeza_de_hogar                       0  61620   0.000000
orientación_sexual                    0  61620   0.000000
etnia                                 0  61620   0.000000
caracterizacion_ciudadano             0  61620   0.000000
empleado                              0  61620   0.000000
barrio_vereda_ciudadano               0  61620   0.000000
estrato                               0  61620   0.000000
comuna_ciudadano                      0  61620   0.000000
nombre_del_beneficio_otorgado         0  61620   0.000000
fecha_de_beneficio_dia                0  61620   0.000000
fecha_de_beneficio_mes                0  61620   0.000000
fecha_de_beneficio_año                0  61620   0.000000
sede_que_otorga_el_beneficio          0  61620   0.000000
fase_del_proceso                      0  61620   0.000000
fase_del_emprendimiento               0  61620   0.000000
como_se_enteró_del_servicio           0  61620   0.000000
subsecretaría_dirección               0  61620   0.000000
nombre_de_la_unidad_o_programa        0  61620   0.000000
nombre_del_proyecto                   0  61620   0.000000

In [ ]:
# Eliminamos la columna zona cuidadano ya que mas del 90% de los datos son nulos

#df["zona_ciudadano"].replace(np.nan, "Unknown", inplace = True)

df = df.drop(columns=["zona_ciudadano"])

In [ ]:
df.shape

(61620, 26)

In [ ]:
df.dtypes

edad                              float64
sexo                               object
etnia                              object
discapacidad                       object
victima                            object
población_campesina                object
estado_civil                       object
nivel_escolaridad                  object
cabeza_de_hogar                    object
orientación_sexual                 object
caracterizacion_ciudadano          object
empleado                           object
estrato                            object
barrio_vereda_ciudadano            object
comuna_ciudadano                   object
nombre_del_beneficio_otorgado      object
fecha_de_beneficio_dia              int64
fecha_de_beneficio_mes              int64
fecha_de_beneficio_año              int64
sede_que_otorga_el_beneficio       object
fase_del_proceso                   object
fase_del_emprendimiento            object
como_se_enteró_del_servicio        object
subsecretaría_dirección            object
nombre_de_la_unidad_o_programa     object
nombre_del_proyecto                object
dtype: object

In [ ]:
# Llenamos los campos vacios de edad con la media

df["edad"].fillna(round(df["edad"].mean(),2), inplace = True)
# Luego convertimos este tipo de dato en entero

df['edad'] = df['edad'].astype(int)

<ipython-input-7-e20269881d22>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["edad"].fillna(round(df["edad"].mean(),2), inplace = True)

In [ ]:
df.edad.isnull().sum()

np.int64(0)

In [ ]:
#Buscamos si los datos nulos fueron corregidos en la totalidad de las columnas

In [ ]:
df.stb.missing()

                                missing  total  percent
edad                                  0  61620      0.0
sexo                                  0  61620      0.0
etnia                                 0  61620      0.0
discapacidad                          0  61620      0.0
victima                               0  61620      0.0
población_campesina                   0  61620      0.0
estado_civil                          0  61620      0.0
nivel_escolaridad                     0  61620      0.0
cabeza_de_hogar                       0  61620      0.0
orientación_sexual                    0  61620      0.0
caracterizacion_ciudadano             0  61620      0.0
empleado                              0  61620      0.0
estrato                               0  61620      0.0
barrio_vereda_ciudadano               0  61620      0.0
comuna_ciudadano                      0  61620      0.0
nombre_del_beneficio_otorgado         0  61620      0.0
fecha_de_beneficio_dia                0  61620      0.0
fecha_de_beneficio_mes                0  61620      0.0
fecha_de_beneficio_año                0  61620      0.0
sede_que_otorga_el_beneficio          0  61620      0.0
fase_del_proceso                      0  61620      0.0
fase_del_emprendimiento               0  61620      0.0
como_se_enteró_del_servicio           0  61620      0.0
subsecretaría_dirección               0  61620      0.0
nombre_de_la_unidad_o_programa        0  61620      0.0
nombre_del_proyecto                   0  61620      0.0

In [ ]:
# Vamos a convertir las columnas 'fecha_de_beneficio_dia'... mes y año en una sola columna que se llame 'fecha_de_beneficio'

df['fecha_de_beneficio'] = pd.to_datetime(df['fecha_de_beneficio_año'].astype(str) + '-' + df['fecha_de_beneficio_mes'].astype(str) + '-' + df['fecha_de_beneficio_dia'].astype(str))

In [ ]:
# Revisamos que quede correcta la columna fecha_de_beneficio
df.head(5)

,edad,sexo,etnia,discapacidad,victima,población_campesina,estado_civil,nivel_escolaridad,cabeza_de_hogar,orientación_sexual,caracterizacion_ciudadano,empleado,estrato,barrio_vereda_ciudadano,comuna_ciudadano,nombre_del_beneficio_otorgado,fecha_de_beneficio_dia,fecha_de_beneficio_mes,fecha_de_beneficio_año,sede_que_otorga_el_beneficio,fase_del_proceso,fase_del_emprendimiento,como_se_enteró_del_servicio,subsecretaría_dirección,nombre_de_la_unidad_o_programa,nombre_del_proyecto,fecha_de_beneficio
0,45,femenino,otros,no,no,no,soltero,tecnico,si,heterosexual,otro,no,3,bello,a1-bello / fuera de medellín,9. intermediacion laboral (registro hoja de v...,16,8,2017,cam - alcaldia de medellin,1. inscripción,no aplica,evento,subsecretaría de creación y fortalecimiento em...,ope,oficina pública de empleo,2017-08-16
1,45,femenino,otros,no,no,no,soltero,tecnico,si,heterosexual,otro,no,3,bello,a1-bello / fuera de medellín,9. intermediacion laboral (registro hoja de v...,16,8,2017,cam - alcaldia de medellin,1. inscripción,no aplica,evento,subsecretaría de creación y fortalecimiento em...,ope,oficina pública de empleo,2017-08-16
2,45,femenino,otros,no,no,no,soltero,tecnico,si,heterosexual,otro,no,3,bello,a1-bello / fuera de medellín,9. intermediacion laboral (registro hoja de v...,16,8,2017,cam - alcaldia de medellin,1. inscripción,no aplica,evento,subsecretaría de creación y fortalecimiento em...,ope,oficina pública de empleo,2017-08-16
3,25,femenino,otros,no,no,no,casado,tecnologo,no,heterosexual,otro,no,2,villa hermosa,08-villa hermosa,9. intermediacion laboral (registro hoja de v...,17,9,2017,ope villa hermosa,1. inscripción,no aplica,voz a voz,subsecretaría de creación y fortalecimiento em...,ope,oficina pública de empleo,2017-09-17
4,30,femenino,otros,no,no,no,soltero,bachiller,si,heterosexual,otro,no,2,villa hermosa,08-villa hermosa,9. intermediacion laboral (registro hoja de v...,15,9,2017,ope villa hermosa,1. inscripción,no aplica,evento,subsecretaría de creación y fortalecimiento em...,ope,oficina pública de empleo,2017-09-15

In [ ]:
# Eliminamos las columnas con el dia, mes y año

df.drop(columns=["fecha_de_beneficio_dia", "fecha_de_beneficio_mes", "fecha_de_beneficio_año"], inplace = True)

In [ ]:
df.head(5)

,edad,sexo,etnia,discapacidad,victima,población_campesina,estado_civil,nivel_escolaridad,cabeza_de_hogar,orientación_sexual,caracterizacion_ciudadano,empleado,estrato,barrio_vereda_ciudadano,comuna_ciudadano,nombre_del_beneficio_otorgado,sede_que_otorga_el_beneficio,fase_del_proceso,fase_del_emprendimiento,como_se_enteró_del_servicio,subsecretaría_dirección,nombre_de_la_unidad_o_programa,nombre_del_proyecto,fecha_de_beneficio
0,45,femenino,otros,no,no,no,soltero,tecnico,si,heterosexual,otro,no,3,bello,a1-bello / fuera de medellín,9. intermediacion laboral (registro hoja de v...,cam - alcaldia de medellin,1. inscripción,no aplica,evento,subsecretaría de creación y fortalecimiento em...,ope,oficina pública de empleo,2017-08-16
1,45,femenino,otros,no,no,no,soltero,tecnico,si,heterosexual,otro,no,3,bello,a1-bello / fuera de medellín,9. intermediacion laboral (registro hoja de v...,cam - alcaldia de medellin,1. inscripción,no aplica,evento,subsecretaría de creación y fortalecimiento em...,ope,oficina pública de empleo,2017-08-16
2,45,femenino,otros,no,no,no,soltero,tecnico,si,heterosexual,otro,no,3,bello,a1-bello / fuera de medellín,9. intermediacion laboral (registro hoja de v...,cam - alcaldia de medellin,1. inscripción,no aplica,evento,subsecretaría de creación y fortalecimiento em...,ope,oficina pública de empleo,2017-08-16
3,25,femenino,otros,no,no,no,casado,tecnologo,no,heterosexual,otro,no,2,villa hermosa,08-villa hermosa,9. intermediacion laboral (registro hoja de v...,ope villa hermosa,1. inscripción,no aplica,voz a voz,subsecretaría de creación y fortalecimiento em...,ope,oficina pública de empleo,2017-09-17
4,30,femenino,otros,no,no,no,soltero,bachiller,si,heterosexual,otro,no,2,villa hermosa,08-villa hermosa,9. intermediacion laboral (registro hoja de v...,ope villa hermosa,1. inscripción,no aplica,evento,subsecretaría de creación y fortalecimiento em...,ope,oficina pública de empleo,2017-09-15

In [ ]:
# Vemos datos duplicados en la columna 'nombre_del_proyecto'
df.nombre_del_proyecto.duplicated().sum()

np.int64(61619)

In [ ]:
# Eliminamos la columna ya que todos estos datos están repetidos y es innecesario tenerlos

df.drop(columns=["nombre_del_proyecto"], inplace = True)

In [ ]:
# Modificamos el tipo de dato de la columna 'estrato' a entero
df['estrato'] = pd.to_numeric(df['estrato'], errors='coerce').astype('Int64')

In [ ]:
df.estrato.isnull().sum()

np.int64(56951)

In [ ]:
# Llenamos datos vacios con la media

df["estrato"].fillna(round(df["estrato"].mean()), inplace = True)

<ipython-input-18-393ef68d09f0>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["estrato"].fillna(round(df["estrato"].mean()), inplace = True)

In [ ]:
df.dtypes

edad                                       int64
sexo                                      object
etnia                                     object
discapacidad                              object
victima                                   object
población_campesina                       object
estado_civil                              object
nivel_escolaridad                         object
cabeza_de_hogar                           object
orientación_sexual                        object
caracterizacion_ciudadano                 object
empleado                                  object
estrato                                    Int64
barrio_vereda_ciudadano                   object
comuna_ciudadano                          object
nombre_del_beneficio_otorgado             object
sede_que_otorga_el_beneficio              object
fase_del_proceso                          object
fase_del_emprendimiento                   object
como_se_enteró_del_servicio               object
subsecretaría_dirección                   object
nombre_de_la_unidad_o_programa            object
fecha_de_beneficio                datetime64[ns]
dtype: object

In [ ]:
#Descargamos la data limpia con el prefijo CLEAN en el nombramiento

In [ ]:
df.to_csv("/content/CLEAN-atenciones_oficina_publica_de_empleo_ope.csv")

In [ ]:
#Leemos la data limpia mostrando solo N cantidad de filas para combrobar la limpieza

In [ ]:
df = pd.read_csv("/content/CLEAN-atenciones_oficina_publica_de_empleo_ope.csv")
df.head(15)

,Unnamed: 0,edad,sexo,etnia,discapacidad,victima,población_campesina,estado_civil,nivel_escolaridad,cabeza_de_hogar,orientación_sexual,caracterizacion_ciudadano,empleado,estrato,barrio_vereda_ciudadano,comuna_ciudadano,nombre_del_beneficio_otorgado,sede_que_otorga_el_beneficio,fase_del_proceso,fase_del_emprendimiento,como_se_enteró_del_servicio,subsecretaría_dirección,nombre_de_la_unidad_o_programa,fecha_de_beneficio
0,0,45,femenino,otros,no,no,no,soltero,tecnico,si,heterosexual,otro,no,3,bello,a1-bello / fuera de medellín,9. intermediacion laboral (registro hoja de v...,cam - alcaldia de medellin,1. inscripción,no aplica,evento,subsecretaría de creación y fortalecimiento em...,ope,2017-08-16
1,1,45,femenino,otros,no,no,no,soltero,tecnico,si,heterosexual,otro,no,3,bello,a1-bello / fuera de medellín,9. intermediacion laboral (registro hoja de v...,cam - alcaldia de medellin,1. inscripción,no aplica,evento,subsecretaría de creación y fortalecimiento em...,ope,2017-08-16
2,2,45,femenino,otros,no,no,no,soltero,tecnico,si,heterosexual,otro,no,3,bello,a1-bello / fuera de medellín,9. intermediacion laboral (registro hoja de v...,cam - alcaldia de medellin,1. inscripción,no aplica,evento,subsecretaría de creación y fortalecimiento em...,ope,2017-08-16
3,3,25,femenino,otros,no,no,no,casado,tecnologo,no,heterosexual,otro,no,2,villa hermosa,08-villa hermosa,9. intermediacion laboral (registro hoja de v...,ope villa hermosa,1. inscripción,no aplica,voz a voz,subsecretaría de creación y fortalecimiento em...,ope,2017-09-17
4,4,30,femenino,otros,no,no,no,soltero,bachiller,si,heterosexual,otro,no,2,villa hermosa,08-villa hermosa,9. intermediacion laboral (registro hoja de v...,ope villa hermosa,1. inscripción,no aplica,evento,subsecretaría de creación y fortalecimiento em...,ope,2017-09-15
5,5,24,femenino,otros,no,no,no,soltero,profesional,no,heterosexual,otro,no,2,bello,07-robledo,9. intermediacion laboral (registro hoja de v...,cam - alcaldia de medellin,1. inscripción,no aplica,no dato,subsecretaría de creación y fortalecimiento em...,ope,2017-10-09
6,6,30,femenino,otros,no,no,no,soltero,tecnologo,no,heterosexual,otro,no,2,bello,07-robledo,9. intermediacion laboral (registro hoja de v...,cam - alcaldia de medellin,1. inscripción,no aplica,no dato,subsecretaría de creación y fortalecimiento em...,ope,2017-10-10
7,7,22,masculino,otros,no,no,no,soltero,tecnico,no,heterosexual,otro,no,3,bello,07-robledo,9. intermediacion laboral (registro hoja de v...,cam - alcaldia de medellin,1. inscripción,no aplica,voz a voz,subsecretaría de creación y fortalecimiento em...,ope,2017-09-13
8,8,20,femenino,otros,no,si,no,soltero,tecnico,no,heterosexual,otro,no,1,no dato,08-villa hermosa,9. intermediacion laboral (registro hoja de v...,ope villa hermosa,1. inscripción,no aplica,voz a voz,subsecretaría de creación y fortalecimiento em...,ope,2017-09-01
9,9,20,femenino,otros,no,si,no,soltero,tecnico,no,heterosexual,otro,no,1,no dato,08-villa hermosa,9. intermediacion laboral (registro hoja de v...,ope villa hermosa,1. inscripción,no aplica,voz a voz,subsecretaría de creación y fortalecimiento em...,ope,2017-09-01
10,10,20,femenino,otros,no,no,no,unión libre,tecnico,si,heterosexual,otro,no,3,san lucas,14-el poblado,9. intermediacion laboral (registro hoja de v...,ope villa hermosa,1. inscripción,no aplica,evento,subsecretaría de creación y fortalecimiento em...,ope,2017-08-28
11,11,27,femenino,otros,no,si,no,unión libre,tecnologo,no,heterosexual,otro,no,2,no dato,08-villa hermosa,2. orientacion (ope),ope villa hermosa,1. inscripción,no aplica,evento,subsecretaría de creación y fortalecimiento em...,ope,2017-09-18
12,12,23,femenino,otros,no,no,no,soltero,tecnico,no,heterosexual,otro,no,2,campo valdez,04-aranjuez,9. intermediacion laboral (registro hoja de v...,ope manrique,5. prestación del servicio,no aplica,voz a voz,subsecretaría de creación y fortalecimiento em...,ope,2017-09-03
13,13,25,masculino,otros,no,no,no,soltero,tecnologo,si,heterosexual,otro,no,1,bello,07-robledo,9. intermediacion laboral (actualización hoja...,cam - alcaldia de medellin,5. prestación del servicio,no aplica,no dato,subsecretaría de creación y fortalecimiento em...,ope,2017-08-16
14,14,47,femenino,otros,no,si,no,unión libre,primaria,si,heterosexual,otro,no,2,bello,07-robledo,9. intermediacion laboral (registro hoja de v...,cam - alcaldia de medellin,1. inscripción,no aplica,voz a voz,subsecretaría de creación y fortalecimiento em...,ope,2017-08-28